import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import { execFile } from "child_process";
import { promisify } from "util";
import fs from "fs/promises";
import path from "path";

const exec = promisify(execFile);

const SERVER_URL = process.env.SERVER_URL || "http://localhost:3100/mcp";
const AGENT_NAME = process.env.AGENT_NAME || "test-worker-1";

async function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  console.log(`[TestWorker] Connecting to ${SERVER_URL}...`);

  // Create MCP client
  const client = new Client({
    name: AGENT_NAME,
    version: "0.1.0",
  });

  const transport = new StreamableHTTPClientTransport(new URL(SERVER_URL));
  await client.connect(transport);
  console.log("[TestWorker] Connected to MCP server");

  // Step 1: Join the project
  console.log("[TestWorker] Joining project...");
  const joinResult = await client.callTool({
    name: "join_project",
    arguments: {
      agent_name: AGENT_NAME,
      capabilities: ["typescript", "node.js"],
    },
  });
  const joinData = JSON.parse((joinResult.content as Array<{ text: string }>)[0].text);
  console.log("[TestWorker] Joined:", joinData.project?.name);
  const agentId = joinData.agentId;
  const workspace = joinData.workspace;

  if (!agentId || !workspace) {
    console.error("[TestWorker] Failed to join — no agentId or workspace");
    process.exit(1);
  }

  // Step 2: Get a task
  console.log("[TestWorker] Requesting task...");
  const taskResult = await client.callTool({
    name: "get_my_task",
    arguments: { agent_id: agentId },
  });
  const taskData = JSON.parse((taskResult.content as Array<{ text: string }>)[0].text);

  if (!taskData.task) {
    console.log("[TestWorker] No tasks available:", taskData.message);
    await client.close();
    return;
  }

  const task = taskData.task;
  console.log(`[TestWorker] Got task: ${task.id} — ${task.title}`);
  console.log(`[TestWorker] Branch: ${task.branch}`);

  // Step 3: Report status
  await client.callTool({
    name: "report_status",
    arguments: {
      agent_id: agentId,
      task_id: task.id,
      status: "in_progress",
      description: "Starting work on the task",
    },
  });

  // Step 4: Do the "work" — write a placeholder file on the branch
  console.log("[TestWorker] Working on task...");
  await exec("git", ["checkout", task.branch], { cwd: workspace });

  for (const filePath of task.filePaths) {
    const fullPath = path.join(workspace, filePath);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(
      fullPath,
      `// ${task.title}\n// Generated by ${AGENT_NAME}\n// Task: ${task.id}\n\n` +
        `export {}; // placeholder implementation\n`
    );
  }

  await exec("git", ["add", "."], { cwd: workspace });
  await exec("git", ["commit", "-m", `${task.id}: ${task.title}`], { cwd: workspace });
  await exec("git", ["checkout", "main"], { cwd: workspace });

  console.log("[TestWorker] Code committed to branch");

  // Step 5: Check updates before submitting
  await client.callTool({
    name: "check_updates",
    arguments: { agent_id: agentId, task_id: task.id },
  });

  // Step 6: Submit
  console.log("[TestWorker] Submitting...");
  const submitResult = await client.callTool({
    name: "submit_result",
    arguments: { agent_id: agentId, task_id: task.id },
  });
  console.log("[TestWorker] Submitted:", JSON.parse((submitResult.content as Array<{ text: string }>)[0].text).message);

  // Step 7: Poll for validation result
  console.log("[TestWorker] Polling for result...");
  for (let i = 0; i < 30; i++) {
    await sleep(2000);
    const updateResult = await client.callTool({
      name: "check_updates",
      arguments: { agent_id: agentId, task_id: task.id },
    });
    const updates = JSON.parse((updateResult.content as Array<{ text: string }>)[0].text);
    console.log(`[TestWorker] Status: ${updates.taskStatus}`);

    if (updates.taskStatus === "accepted") {
      console.log("[TestWorker] Task ACCEPTED!");
      if (updates.validationFeedback) console.log(`[TestWorker] Feedback: ${updates.validationFeedback}`);
      break;
    } else if (updates.taskStatus === "rejected") {
      console.log("[TestWorker] Task REJECTED");
      console.log(`[TestWorker] Feedback: ${updates.validationFeedback}`);
      break;
    }
  }

  await client.close();
  console.log("[TestWorker] Done");
}

main().catch((err) => {
  console.error("[TestWorker] Error:", err);
  process.exit(1);
});
