#!/usr/bin/env bash
set -euo pipefail

# Tuned KernelBench profile based on recent runs:
# - full-first archive objective (implemented in search loop)
# - moderate full parallelism on a single L40S eval worker
# - higher full-eval cadence for better quick/full alignment

WORKSPACE="${1:-${KERNELSWARM_WORKSPACE:-.runs/search-kernelbench-v2}}"

export KERNELSWARM_WORKSPACE="$WORKSPACE"
export KERNELSWARM_PROBLEM_ID="${KERNELSWARM_PROBLEM_ID:-kernelbench_v1}"
export KERNELSWARM_BACKEND="${KERNELSWARM_BACKEND:-cuda}"

export KERNELSWARM_MAX_MINUTES="${KERNELSWARM_MAX_MINUTES:-20}"
export KERNELSWARM_MAX_ITERATIONS="${KERNELSWARM_MAX_ITERATIONS:-5000}"
export KERNELSWARM_TOKEN_BUDGET="${KERNELSWARM_TOKEN_BUDGET:-2000000}"

export KERNELSWARM_GENERATORS="${KERNELSWARM_GENERATORS:-32}"
export KERNELSWARM_JUDGES="${KERNELSWARM_JUDGES:-32}"
export KERNELSWARM_NEMOTRON_PROVIDER="${KERNELSWARM_NEMOTRON_PROVIDER:-deepinfra}"
export KERNELSWARM_NEMOTRON_MAX_CONCURRENT_REQUESTS="${KERNELSWARM_NEMOTRON_MAX_CONCURRENT_REQUESTS:-32}"

export KERNELSWARM_REMOTE_EVAL_URL="${KERNELSWARM_REMOTE_EVAL_URL:-http://127.0.0.1:18080}"
export KERNELSWARM_AUTO_TUNNEL="${KERNELSWARM_AUTO_TUNNEL:-1}"
export KERNELSWARM_TUNNEL_MODE="${KERNELSWARM_TUNNEL_MODE:-ssh}"
export KERNELSWARM_TUNNEL_TARGET="${KERNELSWARM_TUNNEL_TARGET:-kernel-swarm-eval-new-2}"
export KERNELSWARM_TUNNEL_REMOTE_HOST="${KERNELSWARM_TUNNEL_REMOTE_HOST:-127.0.0.1}"
export KERNELSWARM_TUNNEL_REMOTE_PORT="${KERNELSWARM_TUNNEL_REMOTE_PORT:-8080}"

export KERNELSWARM_PROPOSAL_WORKERS="${KERNELSWARM_PROPOSAL_WORKERS:-24}"
export KERNELSWARM_QUICK_EVAL_WORKERS="${KERNELSWARM_QUICK_EVAL_WORKERS:-12}"
export KERNELSWARM_FULL_EVAL_WORKERS="${KERNELSWARM_FULL_EVAL_WORKERS:-4}"
export KERNELSWARM_MAX_INFLIGHT_PROPOSALS="${KERNELSWARM_MAX_INFLIGHT_PROPOSALS:-96}"
export KERNELSWARM_MAX_INFLIGHT_QUICK_EVALS="${KERNELSWARM_MAX_INFLIGHT_QUICK_EVALS:-24}"
export KERNELSWARM_MAX_INFLIGHT_FULL_EVALS="${KERNELSWARM_MAX_INFLIGHT_FULL_EVALS:-8}"
export KERNELSWARM_PERIODIC_FULL_EVAL_EVERY_QUICK="${KERNELSWARM_PERIODIC_FULL_EVAL_EVERY_QUICK:-10}"
export KERNELSWARM_FORCE_FIRST_FULL_PER_ISLAND="${KERNELSWARM_FORCE_FIRST_FULL_PER_ISLAND:-1}"

export KERNELSWARM_KB_LEVEL="${KERNELSWARM_KB_LEVEL:-1}"
export KERNELSWARM_KB_PROBLEM_ID="${KERNELSWARM_KB_PROBLEM_ID:-23}"
export KERNELSWARM_KB_DATASET_SOURCE="${KERNELSWARM_KB_DATASET_SOURCE:-local}"
export KERNELSWARM_KB_REPO_PATH="${KERNELSWARM_KB_REPO_PATH:-$HOME/KernelBench}"
export KERNELSWARM_KB_PRECISION="${KERNELSWARM_KB_PRECISION:-fp32}"
export KERNELSWARM_KB_QUICK_PERF_TRIALS="${KERNELSWARM_KB_QUICK_PERF_TRIALS:-4}"
export KERNELSWARM_KB_FULL_PERF_TRIALS="${KERNELSWARM_KB_FULL_PERF_TRIALS:-20}"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
exec "$SCRIPT_DIR/run_medium_20m.sh" "$WORKSPACE"
